Serendipity-Job:
  BootApp:
    - Serendipity\Job\Config\ConfigProvider
    - Serendipity\Job\Event\EventProvider
    - Serendipity\Job\Logger\LoggerProvider
    ## 服务启动一定要在最后
    - Serendipity\Job\Server\ServerProvider
Manage-Job:
  BootApp:
    - Serendipity\Job\Config\ConfigProvider
    - Serendipity\Job\Logger\LoggerProvider
    - Serendipity\Job\Event\EventProvider
